#!/usr/bin/env ruby
# frozen_string_literal: true

require 'aikido-ruby-client'

client = Aikido::Client.new

result = client.public_send(ARGV[0], *ARGV[1..-1])

if result.is_a?(Aikido::PaginatedResponse)
  puts result.to_a
else
  puts result
end
